const ready=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
export function indicatorStatuses({calc={},trend={},technical={},features={},engines={}}={}){
 const rows=[],add=(name,value,status,reason='')=>rows.push({name,value,status,reason});
 for(const [name,key] of Object.entries({'EMA 9':'e9','EMA 21':'e21','EMA 50':'e50','EMA 200':'e200','RSI':'rsi','MACD':'macd','MACD signal':'signal','MACD histogram':'hist','VWAP':'vwap'})){const v=calc[key]?.at(-1);add(name,ready(v)?Number(v):null,ready(v)?'READY':'WAIT','Closed-candle calculation; VWAP requires real volume');}
 for(const [name,key] of Object.entries({'Supertrend':'supertrend','ADX':'adx','+DI':'plusDI','−DI':'minusDI','ATR':'atr'})){const v=trend[key]?.at(-1);add(name,ready(v)?Number(v):null,ready(v)?'READY':'WAIT');}
 for(const [name,row] of Object.entries(technical)){if(!row||typeof row!=='object'||!('signal' in row))continue;add(name,row.value,row.value===null||row.value===undefined?'WAIT':row.signal||'READY',row.reason||'');}
 for(const key of ['keltner','choppiness','aroon','cci','mfi','obv','cmf','relativeVolume','volumeProfile','previousDay','previousWeek','orb','gap','regime','sessionQuality']){const v=features[key];add(key,v??null,v===null||v===undefined?'WAIT':'READY',features.ready?'Computed from closed OHLCV':'Waiting for valid closed candles');}
 for(const [name,row] of Object.entries(engines))add(name,row?.state??row?.signal??row?.overall??null,row?'CONNECTED':'WAIT',row?.reason||row?.reasons?.join(' · ')||'');
 return rows;
}
export function renderIndicatorStatuses(input){const host=document.getElementById('smrt-indicator-status');if(!host)return;const table=document.createElement('table');const head=document.createElement('tr');for(const s of ['Indicator / engine','Status','Value','Reason']){const th=document.createElement('th');th.textContent=s;head.append(th);}table.append(head);for(const row of indicatorStatuses(input)){const tr=document.createElement('tr');for(const value of [row.name,row.status,row.value,row.reason]){const td=document.createElement('td');td.textContent=value===null?'Unavailable':typeof value==='object'?JSON.stringify(value):String(value);tr.append(td);}table.append(tr);}host.replaceChildren(table);}
