[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/chatgpt"
  to = "/.netlify/functions/chatgpt"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://superb-kitsune-6862e1.mohanbhyri.workers.dev/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
